#! usr/bin/env php
<?php

namespace Behavioral\Memento;

require_once 'vendor/autoload.php';

$originator = new Originator();
$caretaker  = new Caretaker();

try {
    $originator->setState("state is on");
    $caretaker->save(new Memento($originator));
    echo $originator->getState() . "\n";

    $originator->setState("state is off");
    $caretaker->save(new Memento($originator));
    echo $originator->getState() . "\n";

    $originator->setState("state is empty");
    echo $originator->getState() . "\n";

    $originator->setState($caretaker->undo()->getMemento()->getState());
    echo "Restoring state...\n" . $originator->getState() . "\n";

    $originator->setState($caretaker->undo()->getMemento()->getState());
    echo "Restoring state...\n" . $originator->getState() . "\n";
} catch (\Throwable $th) {
    echo "Caught exception: ", $th->getMessage(), "\n";
}
