#! usr/bin/env php
<?php

namespace Behavioral\Memento;

require_once 'vendor/autoload.php';

$originator = new Originator();
$caretaker  = new Caretaker();

$originator->setState("On");
$caretaker->setMemento(new Memento($originator->getState()));
$originator->printState();

$originator->setState("Off");
$originator->printState();

$originator->getRestoringState($caretaker->getMemento());
$originator->printState();
