#! usr/bin/env php
<?php

namespace Behavioral\Memento;

require_once 'vendor/autoload.php';

$originator = new Originator();
$caretaker  = new Caretaker();

$originator->setState(new StateType('on'));
$caretaker->setMemento(new Memento($originator));
$originator->printState();

$originator->setState(new StateType('off'));
$originator->printState();

$originator->setState($caretaker->getMemento()->getState());
$originator->printState();
